# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16J4VzYkFjMbZZbMPCVJjmx1BELutKDe6
"""

import streamlit as st
import numpy as np
import joblib

# 🔴 IMPORTANT: import sklearn classes USED DURING TRAINING
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Load model AFTER imports
model = joblib.load("manipulation_model.pkl")

st.set_page_config(page_title="Financial Manipulation Detector")

st.title("📊 Financial Manipulation Prediction")
st.write("Predict whether company financial data is manipulated")

st.divider()

# ---- INPUT FIELDS ----
dsri = st.number_input("DSRI", value=1.0)
gmi = st.number_input("GMI", value=1.0)
aqi = st.number_input("AQI", value=1.0)
sgi = st.number_input("SGI", value=1.0)
depi = st.number_input("DEPI", value=1.0)
sgai = st.number_input("SGAI", value=1.0)
lvgi = st.number_input("LVGI", value=1.0)
tata = st.number_input("TATA", value=0.0)

X = np.array([[dsri, gmi, aqi, sgi, depi, sgai, lvgi, tata]])

if st.button("Predict"):
    prediction = model.predict(X)[0]

    if prediction == 1:
        st.error("⚠️ Data is likely MANIPULATED")
    else:
        st.success("✅ Data is NOT manipulated")